import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react'
import '@/app/globals.css'
import { TanstackQueryProvider } from '@/configs/tanstack-query/provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface CommonLayoutProps {
  children: React.ReactNode;
  title: string;
}

export default function CommonLayout({ children, title }: CommonLayoutProps) {

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <h1 className="text-2xl font-bold mb-4">{title}</h1>
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  )
}